# Generated by Django 3.2.9 on 2021-11-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_name',
            new_name='image_name',
        ),
    ]
